'use strict';

function _fetchProducts() {
    return [
        {itemId: 1,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 2,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 3,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 4,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 5,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 6,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 7,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 8,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 1,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 2,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 3,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 4,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 5,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 6,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 7,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 8,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 1,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 2,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 3,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 4,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 5,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 6,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 7,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
        {itemId: 8,
            itemName: 'mango people t-shirt',
            itemPrice: '52$',
        },
    ];
}

export function _structureProducts() {
    let goodsAllBlocks = [];
    const goods = _fetchProducts();
    for (let i = 0; i < goods.length; i = i + 8) {
        goodsAllBlocks.push(goods.slice(i, i + 8));
    }
    return goodsAllBlocks;
}



